<AutoPilot:project xmlns:AutoPilot="com.autoesl.autopilot.project" top="master_top" name="prj_impulse_test.prj">
    <includePaths/>
    <libraryFlag/>
    <files>
        <file name="../../src/main.cpp" sc="0" tb="1" cflags=" -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed -Wno-unknown-pragmas" csimflags=" -Wno-unknown-pragmas" blackbox="false"/>
        <file name="../../src/picture_txt/pic_data.txt" sc="0" tb="1" cflags=" -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed -Wno-unknown-pragmas" csimflags=" -Wno-unknown-pragmas" blackbox="false"/>
        <file name="../../src/output_result/out.txt" sc="0" tb="1" cflags=" -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed -Wno-unknown-pragmas" csimflags=" -Wno-unknown-pragmas" blackbox="false"/>
        <file name="src/deQAM_to_pixl/data2pic.h" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/code/include -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/ext/dcmt/dcmt/include" csimflags="" blackbox="false"/>
        <file name="src/deQAM_to_pixl/data2pic.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/code/include -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/ext/dcmt/dcmt/include" csimflags="" blackbox="false"/>
        <file name="src/deQAM_to_pixl/data_out_main.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/code/include -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/ext/dcmt/dcmt/include" csimflags="" blackbox="false"/>
        <file name="src/deQAM_to_pixl/deQAM.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/code/include -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/ext/dcmt/dcmt/include" csimflags="" blackbox="false"/>
        <file name="src/channel_stream/channel_gen.h" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/code/include -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/ext/dcmt/dcmt/include" csimflags="" blackbox="false"/>
        <file name="src/channel_stream/channel_gen.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/code/include -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/ext/dcmt/dcmt/include" csimflags="" blackbox="false"/>
        <file name="src/channel_stream/rand_func.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/code/include -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/ext/dcmt/dcmt/include" csimflags="" blackbox="false"/>
        <file name="src/channel_stream/rand.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/code/include -I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/HLS_Final_Channel_Model/ext/dcmt/dcmt/include" csimflags="" blackbox="false"/>
        <file name="src/QAM/qam.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/QAM/qam.hpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/fft/fft.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/fft/fft.hpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/picture_to_symbol/pixl_to_symbol.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/picture_to_symbol/pixl_to_symbol.h" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/top_module.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/top_module.hpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/pilot_insertion/pilot_insertion.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/pilot_insertion/pilot_insertion.h" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/CP_insertion/Cp_insertion.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/CP_insertion/Cp_insertion.h" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/Tx.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/Tx.h" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/AWGN.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/AWGN.h" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/Rx.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/Rx.h" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/data_path.hpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/equalizer/equalizer.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/equalizer/equalizer.hpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/master_top.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/master_top.h" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/master_mem/stream2master.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/master_mem/stream2master.h" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/master_mem/stream2master_output_QAM.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/master_mem/stream2master_output_QAM.h" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/master_mem/master2stream.cpp" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
        <file name="src/master_mem/master2stream.h" sc="0" tb="false" cflags="-I/users/course/2022S/HLS17000000/g110064539/OFDM_Implemented_by_HLS/without_II_violation_host/host/streaming_free_running_k2k/src/dsp/L1/include/hw/vitis_fft/fixed" csimflags="" blackbox="false"/>
    </files>
    <solutions>
        <solution name="solution1" status=""/>
    </solutions>
    <Simulation argv="">
        <SimFlow name="csim" setup="false" optimizeCompile="false" clean="false" ldflags="" mflags=""/>
    </Simulation>
</AutoPilot:project>

